services:

  # ──────────────────────────────────────
  #  BASE DE DONNÉES
  # ──────────────────────────────────────
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: monMotDePasseSuperSecret
      MYSQL_DATABASE: vod_db
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "11085:3306"

  # ──────────────────────────────────────
  #  API GATEWAY
  # ──────────────────────────────────────
  gateway:
    image: sanndobtg/vod-gateway:latest
    ports:
      - "11080:11080"
    depends_on:
      - api-user
      - api-reservation
      - api-review

  # ──────────────────────────────────────
  #  API USER
  # ──────────────────────────────────────
  api-user:
    image: sanndobtg/vod-api-user:latest
    ports:
      - "11081:11081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/vod_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: monMotDePasseSuperSecret
    depends_on:
      - mariadb

  # ──────────────────────────────────────
  #  API RESERVATION
  # ──────────────────────────────────────
  api-reservation:
    image: sanndobtg/vod-api-reservation:latest
    ports:
      - "11082:11082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/vod_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: monMotDePasseSuperSecret
    depends_on:
      - mariadb

  # ──────────────────────────────────────
  #  API REVIEW
  # ──────────────────────────────────────
  api-review:
    image: sanndobtg/vod-api-review:latest
    ports:
      - "11083:11083"
    environment:
      MONGODB_URI: mongodb://obiwan:27017
    depends_on:
      - mariadb

  # ──────────────────────────────────────
  #  API POSTER (à ajouter plus tard)
  # ──────────────────────────────────────
  #api-poster:
  #  image: sanndobtg/vod-api-poster:latest
  #  ports:
  #    - "11084:11084"
  #  environment:
  #    MONGODB_URI: mongodb://obiwan:27017