server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # API Reservation
        - id: api-reservation
          uri: http://api-reservation:PORT_RESERVATION
          predicates:
            - Path=/reservations/**

        # API User
        - id: api-user
          uri: http://api-user:PORT_USER
          predicates:
            - Path=/users/**

        # API Review (à compléter)
        #- id: api-review
        #  uri: http://api-review:PORT_REVIEW
        #  predicates:
        #    - Path=/reviews/**

        # API Poster (à compléter)
        #- id: api-poster
        #  uri: http://api-poster:PORT_POSTER
        #  predicates:
        #    - Path=/posters/**