server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # Configuration CORS : Autorise ton frontend à parler à la Gateway
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # Route pour l'API USER (Comptes)
        - id: api-user
          uri: http://api-user:8082
          predicates:
            - Path=/comptes/**

        # Route pour l'API RESERVATION (Réservations et Films)
        - id: api-reservation
          uri: http://api-reservation:8081
          predicates:
            - Path=/reservations/**, /films/**

        # Route pour l'API REVIEW (Commentaires)
        - id: api-review
          uri: http://api-review:8083
          predicates:
            - Path=/reviews/**

        # API Poster
        - id: api-poster
          uri: http://api-poster:11084
          predicates:
            - Path=/posters/**
